name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: SSH into EC2 and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PRODUCTION_HOST }}
          username: ${{ secrets.PRODUCTION_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "🔗 Connected to EC2!"
            cd ~/energy-forecast-api || git clone https://github.com/bilguunbilegt/energy-forecast-api.git && cd energy-forecast-api
            git pull origin main
            docker build -t myrepo/energy-forecast-api:latest .
            docker stop energy-api || true
            docker rm energy-api || true
            docker run -d --name energy-api -p 5000:5000 myrepo/energy-forecast-api:latest
            echo "🚀 Deployment Successful!"
